---
- name: Timezone | Symlink the correct localtime - pt.1
  file:
    path: /etc/localtime
    state: absent

- name: Timezone | Symlink the correct localtime - pt.2 (/etc/localtime)
  file: 
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link
    owner: root
    group: root
    mode: 0644

- name: Timezone | Make sure the dependencies are installed
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - tzdata
    - ntpdate

- name: Timezone | Update the hardware clock
  command:
    dpkg-reconfigure -f noninteractive tzdata

- name: Timezone | Configure the ntp servers (/etc/ntp.conf)
  template:
    src: etc_ntp.conf.j2
    dest: /etc/ntp.conf

- name: Make sure ntpd is absent
  apt:
    name: ntp
    state: absent

- name: Set ntpdate job
  cron:
    name: ntpdate
    job: "/usr/sbin/ntpdate -bs {{ ntp_server }}"
    minute: "0"
    hour: "*/12"
    weekday: "*"
    day: "*"
    month: "*"
    state: present
